export * from "./shadcn-avatar-a"
export * from "./shadcn-avatar-b"
export * from "./shadcn-avatar-c"
export * from "./shadcn-avatar-d"
export * from "./shadcn-avatar-e"
export * from "./shadcn-avatar-f"
